### ISSUE TITLE
4kHz vs 5kHz

### ISSUE THREAD

**Issue by awgymer** [hasindu2008/squigulator#15]
Can this tool account for differences between the 4kHz and 5kHz sampling frequency (switchover after ONT sequencing software version `23.04`)?

**Comment by hasindu2008** [comment]
Yes. The latest [squigulator v0.3.0](https://github.com/hasindu2008/squigulator/releases/tag/v0.3.0) with the -x dna-r10-min and -x dna-r10-prom profiles generate 5KHz data by default. If you want old 4KHz data, specify -f 4000 along with -x dna-r10-min or -x dna-r10-prom.  Hope it is clear enough?

**Comment by awgymer** [comment]
Ideal, thank you!

**Comment by awgymer** [comment]
Sorry I am now looking at running this and I realise I'm not sure I fully understand the logic behind `-f 4000`? 

This simply sets the coverage depth to 4000 I thought? I'm not sure how this would relate to the data sampling frequency of 4 vs 5 kHz. 

Perhaps I have to just use two versions of `squigulator` to get r10 data at both 4k and 5k sample rate?

**Comment by hasindu2008** [comment]
Oh my bad. I told you the wrong option. You should be using --sample-rate not -f. Sorry about the inconvenience.

**Comment by awgymer** [comment]
No worries, thanks for the clarification
