### ISSUE TITLE
Length for signal

### ISSUE THREAD

**Issue by peiyihe** [hasindu2008/squigulator#19]
Hi,

I'm trying to train some neural network for my raw signal project, so I prepare to train the neural network with squigulator. I'm wondering if it is possible to generate a fixed raw signal and also know its true nucleotide. 

Because I'm trying to train a convolutional neural network or something else to capture the local information in raw signal. So that may need the input has the same width I think. And also would you have some advice?

Thanks!

**Comment by peiyihe** [comment]
To be more specific, is it possible to generate a fixed length raw signal like 1000 sample nodes, and also return its location, which is a little bit different from the current squigulator

**Comment by hasindu2008** [comment]
Hi @peiyihe 
1. Are you looking for dna or rna data?
2. Do you want to generate reads from a reference or do you want to generate from your fastq files?

**Comment by peiyihe** [comment]
Hi,

I'm looking for dna data. For the second question, I think it's better to generate reads from a reference. I need to generate a fixed length raw signal read from a know nulcleotide sequence (reference with location). Thank you very much.

**Comment by hasindu2008** [comment]
Hello

I can think of a few ways to do this in squigulator, but you would have to explore and decide what approach would be the best for your case.

1.  use squigulator with options, `-a file.sam -q reads.fasta` which will write the SAM file containing the coordinates and then a FASTA file with the raw reads. The SAM file has the ss tag and si tag (https://hasindu2008.github.io/squigulator/docs/output.html) which you can then parse to find the mapping between signal samples and read bases. Once you run squigulator, you can parse the slow5 file and create a new slow5 file with each read trimmed to 1000 samples. With the help of the ss and si tags in the SAM file and the reads in the FASTA file, you can determine the true nucleotides.
2. i can provide an option in squigulator that allows you to set the read length to be static, e.g., 100 bases. Then you can set the --dwelll-mean to 10.0 and --dwell-std to 0, this will generate signals such that one nucleotide is always 10 signal samples. 
I think in practical terms, 1 would be more realistic as it captures time warping. 2 is artifical, but could be a useful sustrate for inital testing - the simplest and the easiest case. 

What do you think about this? If I am unclear, let me know so where I should explain in detail.

--- 
Above all please keep in mind that squigulator is a simulator and thus it cannot simulate all the real-world factors in a real-world sequencing run, as is with any simulator. The real-world is complex and there are many known and unknown fcators that a simulator cannot always simulate. So while data from squigulator could be a good place to start your initial work, you should at one point, move towards real-data for the final outcome.

**Comment by peiyihe** [comment]
Hi,

Thank you very much for your help. I think the method 1 and SAM output are exactly what I want. And also thanks you for your advice, I will use squigulator to start my work and finally I will try on the real data!

**Comment by hasindu2008** [comment]
Please feel free to ask if you get lost. Also, keep posted on how you find the training. I am keen to know how different the results are when trained using squigulator simulated data vs real.

**Comment by peiyihe** [comment]
Sure! I will post the result after I try basecalling successfully. Thanks for your help.
