### ISSUE TITLE
short reads

### ISSUE THREAD

**Issue by noncodo** [hasindu2008/squigulator#20]
Looking to replace Scrappie with Squigulator in a signal generation pipeline, but getting warning from short sequences. Is there a solution besides padding the sequences with random/homopolymer sequences?  

Also, program doesn't exit when this exception is thrown.

> [gen_read_common::WARNING] Reference sequence is too short: 147. Expected to be >=200. Open a pull request if you need support for such tiny references. At src/genread.c:161

**Comment by hasindu2008** [comment]
Hey

Do you want to sample random reads from this small reference, or should want to simulate the signal for this whole small contig?

squigulator read.fa -x dna-r9-prom -o reads.blow5 --full-contigs like command will work if later.

**Comment by noncodo** [comment]
`--full-contigs` solves the problem!

**Comment by hasindu2008** [comment]
Clarified the --full-contigs a bit! Thanks.
